### ISSUE TITLE
NCK_unlock_bootloader...

### ISSUE THREAD

**Issue by wutaijieing** [TwizzyIndy/hw_atcmdserver_xcode#2]
fastboot getvar dongle_info
dongle_info: RSA-2048,0xDC01,0xDC02,0x6000,0x5100,0x5000
fastboot oem hwdog certify begin
fastboot oem backdoor get
fastboot oem hwdog certify enc begin
INFOFBLOCK69c825
8ca8f04b9605278c
b6f9fd810f95ca1f
eae884aeabd03d09

fastboot.exe  download:0100 

DATA0100. 

.O.B#...+.q.aq.j
...r.\S7.3R..S..
....: .....GW..8
X.....#J.,m.e.eq

fastboot.exe flash slock 
fastboot.exe  getvar dongle_info
OKAYRSA-2048,0xC01,0xDC02,0x600,0x5100,0x5000
fastboot.exe  oem lock-state info        
 INFO FB LockStat
e: UNLOCKED.    
INFO USER LockSt
ate: UNLOCKED.

**Comment by wutaijieing** [comment]
or..

03-03 04:40:47.346  1327  1505 E         : logPower_print not support
03-03 04:40:47.347  1327  1505 D fingerTest: event.x=:908.0 event.y=:1300.0
03-03 04:40:47.347  1327  1505 D fingerTest: MotionEvent.ACTION_UP
03-03 04:40:47.348  2993  2993 I InputEvent: (881,437)1
03-03 04:40:47.349  1327  1401 W HwPolicyFactoryImpl: mAware is disable
03-03 04:40:47.354  2993  2993 V AudioManager: playSoundEffect   effectType: 0
03-03 04:40:47.355  2993  2993 V AudioManager: querySoundEffectsEnabled...
03-03 04:40:47.358  2993  2993 I VerifySecbootKey: processInput
03-03 04:40:47.368   473   473 D SecAPI  : get HUN SUCCEED in get_psn_by_length
03-03 04:40:47.368   473   473 D SecAPI  : get_hun_by_length: get HUN succeed!
03-03 04:40:47.368   473   473 D SecAPI  : HISI PLATFORM
03-03 04:40:47.378   473   473 D SecAPI  : HISI PLATFORM
03-03 04:40:47.378   473   473 D SecAPI  : get HUN SUCCEED in get_psn_by_length
03-03 04:40:47.378   473   473 D SecAPI  : get_hun_by_length: get HUN succeed!
03-03 04:40:47.378   473   473 D SecAPI  : HISI PLATFORM
03-03 04:40:47.378   473   473 D SecAPI  : data_SHA256: data SH256 computing SUCCEED!
03-03 04:40:47.380   473   473 E SecAPI  : data_RSA_public_decrypt_padding: data RSA decrypt SUCCEED!
03-03 04:40:47.380   473   473 E SecAPI  : signature_verify: hash value not match!
03-03 04:40:47.380   473   473 E SecAPI  : data_set_SHA256_RSA_check_kp: data signature is verified failed!
03-03 04:40:47.380   473   473 E SecAPI  : password_PBK_SHA256_RSA_check_mod: key signature is verified failed!
03-03 04:40:47.380   473   473 E SecAPI  : password_PBK_SHA256_RSA_check_kp: password check failed!
03-03 04:40:47.380   473   473 E SecAPI  : password_PBK_SHA256_RSA_check: password check failed!
03-03 04:40:47.380   473   473 E FACISECMAG: isecurity_key_check: check passwd fail
03-03 04:40:47.380   473   473 E FACISECMAG: isecurity_userkey_check: isecurity_key_check fail
03-03 04:40:47.380   473   473 E         : hw_verify_isecurity_userlock_passwd: isecurity_userkey_check fail.
03-03 04:40:47.381  2993  2993 D         : verify_secboot_key ret = -1
03-03 04:40:47.381  2993  2993 D ManufactureNativeUtils: verifySecbootKey, ret = -1
03-03 04:40:47.381  2993  2993 D ProjectMenuWrapper: verifySecbootKey, ret = -1
03-03 04:40:47.381  2993  2993 E VerifySecbootKey: processInput: verifyKey fail, ret = -1
03-03 04:40:47.389  1327  1712 I NotificationManager: enqueueToast pkg=com.huawei.android.projectmenu callback=android.app.ITransientNotification$Stub$Proxy@a1af698 duration=1

**Comment by TwizzyIndy** [comment]
I'm sorry. This project is really out of date and no longer maintained. Thanks for your interest.

**Comment by kasnria001** [comment]
> I'm sorry. This project is really out of date and no longer maintained. Thanks for your interest.

How do you get the public key?
